### ISSUE TITLE
Combine earnings reports to use a single query.

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#1980]
Currently the earnings / sales graphs perform 2 queries (for each point on the graph):
- a query to get the earnings for that point
- a query to get the sales for that point

When a graph has a lot of points on it, this can result in a LOT of queries being performed.

Since the EDD_Stats class lets us query based on data ranges, we should be able to perform just two queries for a graph but querying the data and then setting it up into an array of timestamp => value pairs, which is exactly what the `EDD_Graph` class expects as its data input anyhow.

**Comment by cklosowski** [comment]
I'm punting this to 2.5. That's going to be a reports focused release, and this one might be in vein if we decide to refactor that page at all.

**Comment by cklosowski** [comment]
Moving to the `EDD_Payment_Stats` class will cause us to refactor how we did #3833. No big deal, just a reminder to notate the changes necessary.

**Comment by cklosowski** [comment]
@sunnyratilal take a look here, has your work on #5118 made this a moot point?

**Comment by sunnyratilal** [comment]
Sales have been combined into a single query - we still need to combine earnings into a single query.

**Comment by sunnyratilal** [comment]
Update on this issue: implementation is very nearly complete.

To Do:
[ ] Add indexing for the returned earnings
[ ] Move all the function calls to use the `get_earnings_by_range()` function

The graphs will need extensive testing to ensure the correct data is being plotted.

**Comment by sunnyratilal** [comment]
The immediate performance and efficiency benefits we've gained from this is fantastic!  Before moving to a single query, we had 321 queries running on the reports page. Now we have 51. 😄

**Comment by sunnyratilal** [comment]
PR opened at #5316 and ready for some testing.

**Comment by pippinsplugins** [comment]
When viewing `This Year`, I see a bunch of notices and warnings. @sunnyratilal check on your end. If you don't see them, I can give the exact warnings / notices. There are a dozen or more.

**Comment by sunnyratilal** [comment]
@pippinsplugins Fixed in 5aa326f3d5e8cc0c5e51aebb708d578e91e0878f

**Comment by pippinsplugins** [comment]
A couple of date ranges still show notices / warnings:

- This Year
- Last Year
- This Week
- Last Week

Also `This Year` and `Last Year` have screwy dates going all the way back to 1970 on the graph:
![screen shot 2016-12-28 at 9 26 40 am](https://cloud.githubusercontent.com/assets/1034109/21525009/cfb3b686-ccdf-11e6-946c-de1b74007948.png)

Custom date ranges don't seem to work at all now:
![screen shot 2016-12-28 at 9 28 09 am](https://cloud.githubusercontent.com/assets/1034109/21525026/fd1101d8-ccdf-11e6-8a05-cd1416dac15c.png)

**Comment by sunnyratilal** [comment]
Hmm not seeing that - all the aforementioned graphs are displaying correctly for me. 🤔 

Are the seeing the errors/incorrectly graphs even after the transients have been cleared?  All of those are cached graphs that's why.

**Comment by pippinsplugins** [comment]
@sunnyratilal just tried again. Same errors.

**Comment by cklosowski** [comment]
@sunnyratilal I'm not seeing errors, but I am seeing incorrect data. I'm seeing `0` for the sales counts. The eranings look right. I've updated the branch to have the new EDD CLI command to create random payments in the last 30 days.:

`wp edd payments create --number=100 --date=random`

That helps build a lot more data.

**Comment by sunnyratilal** [comment]
@pippinsplugins Could you post the errors you're receiving here please?

**Comment by sunnyratilal** [comment]
@cklosowski I'm not seeing any incorrect data.  I'm getting all the data as it is supposed to be?  Perhaps clear transients?

**Comment by cklosowski** [comment]
My issues have gone away, guessing it was transients related. I had cleared them, I thought, but all good now. Let's see what @pippinsplugins errors are and we can then look into merging.

**Comment by sunnyratilal** [comment]
@pippinsplugins Are you still receiving errors?

**Comment by sunnyratilal** [comment]
We cannot progress with #5164 until this is merged.

**Comment by pippinsplugins** [comment]
Will test in the morning again.

**Comment by pippinsplugins** [comment]
@sunnyratilal Looking better!

Custom date ranges (at least those that cross multiple years) do not work. The stats are wrong and the graph doesn't show the full date range.
![screen shot 2017-01-16 at 1 30 36 pm](https://cloud.githubusercontent.com/assets/1034109/21996466/fecf3eee-dbef-11e6-9180-1836dd27e929.png)

**Comment by sunnyratilal** [comment]
@pippinsplugins Can't replicate that.

@SDavisMedia @cklosowski could you test please?

![image](https://cloud.githubusercontent.com/assets/1525554/22003695/802473b2-dc4d-11e6-94a3-b5cd5c2326e3.png)

**Comment by SDavisMedia** [comment]
I can't replicate any of the errors. So I'm all good there as well.

For the data, I thoroughly checked 200+ payments from 2016 to 2017. All sales and earnings were correct for me, even filtered with a custom date range that spanned multiple years. I added and deleted records to check changes to the data. Couldn't break it. 

Damn that's fast. :+1:

**Comment by pippinsplugins** [comment]
I flushed all of my transients to see if that was the cause. Didn't make any difference.

Will try on another install soon.

**Comment by cklosowski** [comment]
@sunnyratilal the predefined ranges seem to be right. i'm having a problem with the custom dates as well though. For example, this is `this month`:
![screen shot 2017-01-17 at 2 18 51 pm](https://cloud.githubusercontent.com/assets/1390124/22040413/f6df3b96-dcbf-11e6-9e30-e01ce9c22a5e.png)


And this is a custom from Jan 1 - Jan 31 of 2017:
![screen shot 2017-01-17 at 2 18 58 pm](https://cloud.githubusercontent.com/assets/1390124/22040432/00e35046-dcc0-11e6-9d96-d4c7af0219f8.png)

Notice the dates are getting cut off on the 15th.

**Comment by SDavisMedia** [comment]
I just replicated that ^^^ ... just with future dates in general, the graph shows no data. 

Filtering by custom dates in February 2017, on `master`, you can still see the flatlined Earnings and Sales run across the bottom. On `issue/1980`, the graph is completely blank.

**Comment by sunnyratilal** [comment]
@SDavisMedia @cklosowski Could you pull and retry please?

**Comment by cklosowski** [comment]
@sunnyratilal @SDavisMedia @pippinsplugins Custom date ranges seem to be working for me now.

**Comment by SDavisMedia** [comment]
Looking good here! :+1:

**Comment by pippinsplugins** [comment]
Nice work here!

**Comment by sunnyratilal** [comment]
Merged into `release/2.7`!

**Comment by pippinsplugins** [comment]
The new `get_earnings_by_range()` and `get_sales_by_range()` methods need to include a filter that allow additional post statuses to be included in the query.

This is important to ensure that plugins like Recurring Payments can inject `edd_subscription` into the list. Without it, the renewal payments in recurring do not get included in the range.

Right now the status is hard coded like this:
```
AND (posts.post_status = 'publish' OR posts.post_status = 'revoked')
```

That could be changed to `AND posts.post_status IN( 'publish', 'revoked' );` with `'publish', 'revoked'` created by exploding an array.

**Comment by sunnyratilal** [comment]
@pippinsplugins PR opened at #5441

**Comment by pippinsplugins** [comment]
@sunnyratilal @cklosowski The new filter name is good but I think it should be extended to the get_sales() and get_earnings methods. We should have a single filter that applies to all four.

**Comment by sunnyratilal** [comment]
@pippinsplugins `get_sales()` and `get_earnings()` has its own filter `edd_count_payments_where` because both of those functions call `edd_count_payments()`.

**Comment by pippinsplugins** [comment]
@cklosowski opinions?

**Comment by pippinsplugins** [comment]
Works great. Closing.
