### ISSUE TITLE
Support additional emails for customers

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#3755]
Right now customers are identified by their email address and each unique email is a different customer.

I think we should add support for adding additional email addresses to customer records. Help Scout does this really well.

Doing this would allow us to associate multiple emails with a single customer record and would resolve this problem:

![screen shot 2015-09-01 at 9 26 00 am](https://cloud.githubusercontent.com/assets/1034109/9606853/7e5a2972-508b-11e5-9b95-879faf5f75a3.png)

**Comment by ghost1227** [comment]
How do you see this working?

**Comment by pippinsplugins** [comment]
My first thought was via a separate column in the customers' DB for email aliases. Probably comma separated.

**Comment by ghost1227** [comment]
Given that a significant amount of the existing setup (re: customer records) is based on email, how would that work? Would we migrate away from that and use something else? Or just have more of a 'primary' vs 'attached' email setup?

**Comment by pippinsplugins** [comment]
No, that's over thinking it.

We simply add another column to the DB and allow alternative addresses to be set. When searching for payments by email, we look both in the primary and alternative columns.

**Comment by michaelbeil** [comment]
This would be phenomenal. Re: Justin Sainton on Twitter, what about a meta approach?

**Comment by JustinSainton** [comment]
My thinking behind that is that it might be tricky to scale that - if the intent was to have a 1:1 relationship between alternate email and DB column.

A meta value, an array of alternate addresses, might prove a more reliable data store for situations where a dev, a junior dev, agency parter, client, client's client, client's cat, cat's caretaker, etc. all need access.

All that to say, @pippinsplugins is right - technical implementation matters less than the actual feature happening. kudos on a great idea :)

**Comment by 1bigidea** [comment]
Just a reminder, if I am doing my job the way you (the developer) want, I'll have my email address attached to multiple end-user accounts.

This problem isn't different from reminding a user from a larger organization to use a generic email address for registering (or recovering a password) rather than a personal one that expires when an employee leaves.

**Comment by pippinsplugins** [comment]
Another problem this helps us solve:

1. Customer purchases something with `name1@test.com` and registers an account (call it ID 1)
2. Customer now has a customer record identified by `name1@test.com` and a `user_id` of `1`
3. Same customer, while logged in, purchases another item but enters `name2@test.com`.
4. Purchase record is now tied to customer record of `name2@test.com` but `user_id` of `1`
5. Two customer records now have the same `user_id` column
6. The second purchase is not available in customer's `Purchase History` since he/she now has two customer records

When processing a purchase for a logged in user, we need to look up customers by the user ID and then alias the second email address entered.

**Comment by zackkatz** [comment]
:+1:

**Comment by pippinsplugins** [comment]
Customer meta table is ready for testing in #4311 so we can get started on this now.

**Comment by pippinsplugins** [comment]
I have this fully functional now in `issue/3755`.

Now I just need to build the UI to display additional emails and allow additional emails to be added / removed from the UI.

**Comment by cklosowski** [comment]
@pippinsplugins should we also allow the ability to `Set as primary` for a customer? would that have any benefit? It could be from either the User or the Admin side.

**Comment by pippinsplugins** [comment]
Yes I think so. I was considering adding a `make_primary()` method that would handle swapping the emails.

**Comment by pippinsplugins** [comment]
@cklosowski How's https://github.com/easydigitaldownloads/easy-digital-downloads/commit/58a278c548eeb48394f71f827e0410ad05a1961c look to you?

**Comment by pippinsplugins** [comment]
We need to block that behavior probably, or at least block it if the email is associated with a customer record that is tied to a different user account.

**Comment by cklosowski** [comment]
:+1: I'll work up some error verbage.

**Comment by cklosowski** [comment]
@pippinsplugins I see two issues with the current method of showing additional emails, and that it leaves us very little room for a good 'management' approach. Adding actions for 'making primary' and 'removing' leaves us with room for icons only which isn't great for usability.

How would you feel about adding a list table below (i know it's not perfect) which would allow us an 'actions' column to make primary and remove, then we could use some repeatable rows logic to create new emails for the user?

**Comment by pippinsplugins** [comment]
I was toying with a list table too. I think I like that better as long as
it indicates which email is primary.

**Comment by cklosowski** [comment]
:+1: Thanks, I'll go that route

**Comment by pippinsplugins** [comment]
I like the idea of including a link on each additional email as well for `Make Primary`.

**Comment by pippinsplugins** [comment]
Looking really good!

We need to add in detection for non-valid emails in the `Add Email` form:
![screen shot 2016-05-23 at 8 16 09 pm](https://cloud.githubusercontent.com/assets/1034109/15489194/3f73454a-2123-11e6-95a5-dcab7d9e0ef2.png)

**Comment by pippinsplugins** [comment]
This appears to all work really well, but here's a side effect I'm not yet sure how to handle.

1. Assume a customer makes two purchases with `customer@test.com`
2. Same customer comes back and makes a purchase with `customer2@test.com` while logged in. This will register `customer2@test.com` as an additional email for the customer. So far so good.
3. The `3 Completed Sales` link goes to Payment History filtered by the customer's email. When a customer has multiple emails, this results in only purchases made by the primary email getting displayed.
4. If an additional email is converted into the primary email, the original purchases made by the previously primary email no longer display when clicking `X Completed Sales`

I think we can fix both issues by changing the `X Completed Sales` link to use the customer ID as the filter instead of the email. This may also require a change to the Payment History table.

**Comment by cklosowski** [comment]
Yeah. Customer ID would be the best solution for the purchase links. I'll make that happen when I fix the invalid email stuff.

**Comment by cklosowski** [comment]
Ok @pippinsplugins just pushed up some improved error handling on the adding of customer emails from admin, it now logs a customer note whenever we use this form to alter the email addresses, and this also makes the completed payments link use a user `customer` query string item that filters the payments list table by customer ID (regardless of what email the customer has)

Next up, preventing a logged in user from purchasing with an email address registered to another customer.

**Comment by cklosowski** [comment]
@easydigitaldownloads/core-devs this is ready for some testing on both the front end (checkout) and backend (customer management screens)

**Comment by cklosowski** [comment]
@easydigitaldownloads/core-devs While testing this, let's also be sure to hit it with Auto-Register enabled. Just to be sure.

**Comment by pippinsplugins** [comment]
Some testing tips:

- Test adding emails to a customer
- Test removing emails
- Test swapping primary emails
- Test purchasing with new email after adding it
- Test purchasing with a new email (one that hasn't been added) while logged in
- Test instantiating `EDD_Customer` with primary and additional emails
- Test adding an email to a customer that already belongs to someone else
- Test searching payment history / customers with primary and secondary emails

**Comment by cklosowski** [comment]
@pippinsplugins I need to get the searches working properly still. I just wanted to make sure we tested the functionality of using/assigning/deleting REALLY fleshed out before we put it in the beta.

**Comment by cklosowski** [comment]
@easydigitaldownloads/core-devs So some feedback on the 'Payments' search. Right now if you type in an email address it's searching the `_edd_payment_email` payment meta. If we change this to search the customer, it's possible that this will miss some payments  for past purchases as those email addresses are not on the customer records, just in teh payment meta.

Should we leave payment search, using the payment meta? I've got the customer search allowing searching by primary and additional email addresses.

**Comment by pippinsplugins** [comment]
@cklosowski I vote we leave payment searh as is for now.

**Comment by mintplugins** [comment]
Tested by doing a checkout with a logged-in user and using a new email address. It works great and adds the new email to the existing customer. However, I noticed the Payment History screen still has the "Customer" column blank. 
<img width="1245" alt="screen shot 2016-05-25 at 2 31 36 pm" src="https://cloud.githubusercontent.com/assets/1638128/15551816/ab02b878-2285-11e6-93cb-b5e5ca4e2dd1.png">

**Comment by pippinsplugins** [comment]
Good catch.

**Comment by SDavisMedia** [comment]
I actually can't replicate @mintplugins' issue.

Everything seems to be working well for me, though.

**Comment by cklosowski** [comment]
@mintplugins @pippinsplugins We've decided to not move forward with `Did not work (as noted in previous comments as well):` as it's not going to provide a benefit.

**Comment by cklosowski** [comment]
@mintplugins is that with Auto Register? I'm not experiencing that. All my customers have names wether the purchase was made with the primary or an additional email.

**Comment by cklosowski** [comment]
![screen shot 2016-05-25 at 1 39 04 pm](https://cloud.githubusercontent.com/assets/1390124/15555554/179323b8-227e-11e6-9d41-77e9972a4c11.png)

**Comment by cklosowski** [comment]
@easydigitaldownloads/core-devs  Something else I thought about here this morning, do we want to allow a dropdown in the front-end profile editor to allow a customer to choose their primary email from a list of emails attached to their customer? Also, should they be able to delete an email associated with their account on the front-end as well?

I'm hesitant to allow adding from the front-end in the beginning, but I think setting primary and removing emails could be important.

**Comment by SDavisMedia** [comment]
No clue how this didn't cross my mind but I think yes, they should be able to add, remove, and select primary from the profile editor. I vote definitely.

**Comment by cklosowski** [comment]
@SDavisMedia I think for now adding should be limited to a purchase. This prevents someone from going in and adding a bunch of _known_ email addresses to their account, which would effectively prevent someone from purchasing, as an 'blackhat' method of stopping someone from buying.

**Comment by brashrebel** [comment]
What about requiring verification of every added email address?

**Comment by pippinsplugins** [comment]
I would actually prefer that we _not_ allow customers to ad emails from the frontend. While it's unlikely to be abused, the possibility is there.

We can consider adding it in the future but not right now.

If we do add it, it should definitely require verification, like @brashrebel mentioned.

**Comment by topher1kenobe** [comment]
I wouldn't worry about it.  If someone can't buy they'll email the admin and complain, and then the admin will become aware of the jerk and act accordingly.

**Comment by cklosowski** [comment]
I'm with @pippinsplugins We can add it later, but it has to have a verification system.

**Comment by michaelbeil** [comment]
Agreed on the verification system if/when we add this to the front-end profile editor.

**Comment by cklosowski** [comment]
made some updates to this, there is now a section in the profile editor that does some logic to determine 3 cases:

1. User account with no customer (simply uses the user email address) with a text field
2. User is a customer, but only has one email, so it just gives a text field with the customer email address
3. User is a customer with multiple email addresses, displays a dropdown to pick an existing email address as the new 'primary', which is validated, so someone cannot hack in a new email address, and then moves the previous one to the array, this also updates the user login email, FYI.

**Comment by cklosowski** [comment]
![screen shot 2016-05-26 at 11 23 41 am](https://cloud.githubusercontent.com/assets/1390124/15587085/71433682-233c-11e6-9934-c94c9400f1ed.png)

**Comment by cklosowski** [comment]
![screen shot 2016-05-26 at 11 51 28 am](https://cloud.githubusercontent.com/assets/1390124/15588000/b42425f2-2340-11e6-99bb-f0a0a8e7265e.png)

**Comment by pippinsplugins** [comment]
@cklosowski Let's go ahead and merge into `release/2.6` but leave open.

**Comment by cklosowski** [comment]
Done.

**Comment by SDavisMedia** [comment]
All tests working on my end.

**Comment by pippinsplugins** [comment]
@jchristopher found a bug that caused the `The email address {address} is already in use` error to show even when it shouldnt't: http://d.pr/i/Oeho

Fixed in https://github.com/easydigitaldownloads/easy-digital-downloads/commit/dcff8b5b218e34579af7cbef5423e7a8be8bbbdd

**Comment by topher1kenobe** [comment]
All tests working on my end.

**Comment by mintplugins** [comment]
@cklosowski I am still getting a blank customer on the Downloads > Payment History page. Auto Register is disabled.

**Comment by pippinsplugins** [comment]
@mintplugins Does it show customer missing on view order details or is there an email there? Does the customer just not have a name set perhaps?

**Comment by mintplugins** [comment]
@pippinsplugins The customer just didn't have a name. Carry on  :)

**Comment by pippinsplugins** [comment]
Everything looking good here! Closing :)
