### ISSUE TITLE
Further UX improvements to the Licenses tab

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#4050]
In #3889 we've improved the the License list, and some discussion was made about further improvements to make it less cluttered. Logging this one so @SDavisMedia can work his magic on it.

**Comment by SDavisMedia** [comment]
Not thrilled about the styling just yet but I like the grid display. Jacked some styles from @cklosowski's Extensions page. I'll tweak the styles more soon.

![slack-imgs](https://cloud.githubusercontent.com/assets/2359131/11802557/e3946312-a2a6-11e5-87d4-51251d1ffeba.png)

**Comment by pippinsplugins** [comment]
@SDavisMedia I'm really liking where this is going.

I've fixed the missing parameter bug.

**Comment by SDavisMedia** [comment]
@pippinsplugins Thanks! I'll get back to it soon then. Need to see what I can do to consolidate some CSS between this tab and the Extensions page CSS.

Note: I've added a class to all the settings tabs `.wrap` elements. Wanted/needed it for this and it can be useful for other tabs to help prevent other admin CSS conflicts. https://github.com/easydigitaldownloads/Easy-Digital-Downloads/commit/5f5fb59c10a8c648af966ce7de602f5946dc9c60

Let me know if you or @cklosowski have any issues with that.

**Comment by SDavisMedia** [comment]
@pippinsplugins Still having issues with the license data. Stripe you see in my screenshot is the only one behaving correctly. Can you create all of the license scenarios properly in your system?

**Comment by pippinsplugins** [comment]
@SDavisMedia I was seeing a bit of weirdness. Do you get the same behavior with `release/2.5`?

**Comment by SDavisMedia** [comment]
@pippinsplugins yea same exact thing

**Comment by pippinsplugins** [comment]
Reopening original issue for further investigation.

**Comment by SDavisMedia** [comment]
Sweet deal.

**Comment by cklosowski** [comment]
really liking this @SDavisMedia

**Comment by SDavisMedia** [comment]
![2015-12-17 at 6 19 pm](https://cloud.githubusercontent.com/assets/2359131/11887626/dd8e3240-a4ea-11e5-8d8f-aae33e769dc5.png)

@cklosowski @mindctrl @pippinsplugins Thoughts? Keep in mind the majority of licenses will show either nothing or the light gray box. The c boxes sholored boxes would be rare but easily stand out.

**Comment by pippinsplugins** [comment]
Love it.

**Comment by michaelbeil** [comment]
Looking solid @SDavisMedia.

**Comment by chriscct7** [comment]
With license keys we could perhaps offer a renew link in the license key thing.

**Comment by sumobi** [comment]
Beautiful

**Comment by SDavisMedia** [comment]
@chriscct7 we'll be doing that when 2.5 rolls out https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/3889#issuecomment-146296417

**Comment by pippinsplugins** [comment]
@SDavisMedia Could you go ahead and submit the PR for this so we can start testing it?

**Comment by SDavisMedia** [comment]
@pippinsplugins updated with `release/2.6` and done.

**Comment by cklosowski** [comment]
Looking good to me @SDavisMedia

**Comment by pippinsplugins** [comment]
Thanks @SDavisMedia !

**Comment by pippinsplugins** [comment]
Thoughts on what we can do when no license keys are entered?
![screen shot 2016-05-05 at 9 49 00 pm](https://cloud.githubusercontent.com/assets/1034109/15062942/4035115a-130b-11e6-9469-0d1844d003e1.png)

**Comment by SDavisMedia** [comment]
eh... probably just add one more note in the same place as the others asking the user to input the license key for updates

**Comment by SDavisMedia** [comment]
How's this (updated with `release/2.6`):

![screen shot 2016-05-05 at 8 40 25 pm](https://cloud.githubusercontent.com/assets/2359131/15063777/b227e18e-1301-11e6-96a8-b3cbcdfd941b.png)

**Comment by cklosowski** [comment]
I <3 that.

**Comment by chriscct7** [comment]
2 things which might be already agreed upon but just not in the picture
because its trivial, but can the licenses be in alphabetical order, and is
it possible to do a "view" so to speak for "licenses that need attention"
which would have expired or non-entered license keys

**Comment by pippinsplugins** [comment]
I'm not a fan of the giant white space around the input field when no key has been entered. I'm having a hard time coming up with ways to get rid of it but I'd like to experiment and see what options are.

@chriscct7 That would be really nice but let's not worry about that. One piece at a time.

**Comment by spencerfinnell** [comment]
What about a button to their licenses page on the EDD site?

**Comment by pippinsplugins** [comment]
There's a link at the top of the page.

**Comment by SDavisMedia** [comment]
This is an option if we drop "License" off of the secondary button. If not, there's no room to play unless I switch to only two columns. The form text can't afford to be any smaller than this here.

![screen shot 2016-05-06 at 9 37 04 am](https://cloud.githubusercontent.com/assets/2359131/15079597/48b8f626-136e-11e6-8d6a-8b894145679b.png)

**Comment by pippinsplugins** [comment]
I like that version much better!

**Comment by spencerfinnell** [comment]
I'd be careful about relying on character length. It should be treated as dynamic due to translations. 

What about making the section with the text always up against the button or input and the darker gray expanding down to fill the rest?

**Comment by pippinsplugins** [comment]
Good point.

**Comment by SDavisMedia** [comment]
There was room to play [here](https://github.com/easydigitaldownloads/easy-digital-downloads/issues/4050#issuecomment-217341089) as the bottom text section is design to extend upward based on text length, but you don't like the white space. It's there because once a license is entered, not only will a button appear there, but the text message could become longer and push the bottom section up.

For uniform grids elements, we're either gonna have the white space below the form or gray space below the text (with Spencer's suggestion). Either way, there's no guarantee any of the elements will be the same height at all times because they might not have the same content. This is no different from the type of scenario you see on product displays with different length descriptions but uniform grid elements. http://glui.me/?i=j6oepsu0towx9s5/2016-05-06_at_7.16_PM.png/

**Comment by pippinsplugins** [comment]
@SDavisMedia that screenshot seems to have died. Could you post it again?

**Comment by SDavisMedia** [comment]
@pippinsplugins oops http://glui.me/?i=eu5gq3vtsub2t5r/2016-05-09_at_2.57_PM.png/

**Comment by pippinsplugins** [comment]
Ok let's just go with this version: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/4050#issuecomment-217341089

**Comment by pippinsplugins** [comment]
Just did some more testing of this and it's a really, really significant improvement. Once unit tests, I'm going to merge it.

**Comment by pippinsplugins** [comment]
Merged into `release/2.6`
