### ISSUE TITLE
filesize() being run on external files in process-download.php

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#4329]
I've seen this error twice today:

PHP Warning:  filesize(): stat failed for https://github.com/{redacted}/natural-lite/archive/master.zip in /wp-content/plugins/easy-digital-downloads/includes/process-download.php on line 199

If a file is external, we should never run `filesize()` on it.

**Comment by mintplugins** [comment]
This is the same issue as this: 
https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/4321

I had that exact error message when we were initially discussing this issue:
https://eddwp.slack.com/archives/edd-support/p1455901084001739

**Comment by chriscct7** [comment]
The solution to all of these issues seems to be exactly what me and john talked about last week, which is if we implement a simple if not path or URL in WP content then redirect method, then this ^ would be bypassed as would the other nginx issue. As opposed to trying to hunt down one or more issues without fixing the one we already know exists, we're (based on all the theories I've seen thus far) probably just baindaiding over the real issue, which is that (not path && not in WP content) URLs are being sent to direct.

**Comment by chriscct7** [comment]
Related #4321

**Comment by pippinsplugins** [comment]
@chriscct7 I agree.

**Comment by mintplugins** [comment]
@chriscct7 @pippinsplugins Preventing the issue further up the line seems to make the most sense to me as well.

**Comment by cklosowski** [comment]
This is being done in #4328, and is in PR #4335

**Comment by pippinsplugins** [comment]
I've merged this into `2.5.10-beta` and am sending it to a few users.

**Comment by mintplugins** [comment]
I have a ticket where this is still happening for relative links but not affecting downloads. However it is still causing an error in the server logs:

https://secure.helpscout.net/conversation/191893627/32117/?folderId=749231

**Comment by cklosowski** [comment]
Relative links are local so should have their file size determined.

On Sunday, April 17, 2016, Phil Johnston <notifications@github.com> wrote:

> Reopened #4329
> <https://github.com/easydigitaldownloads/easy-digital-downloads/issues/4329>
> .
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <https://github.com/easydigitaldownloads/easy-digital-downloads/issues/4329#event-630525382>
>


-- 
Sent from Gmail Mobile

**Comment by mintplugins** [comment]
Yes this is for local URLs. The Filesize error is still being triggered. I couldn't see why that would be the case.

**Comment by cklosowski** [comment]
Am I missing something? We 'should' be running a `filesize()` here since the file is local, and not external. The goal of this issue `filesize() being run on external files in process-download.php` has been mitigated.

Looking at the screenshots...the person's file is outside of any recognized path to deliver correctly since we've made it through all the file path checks. All our checks are for things in the content folder, and his isn't, but it's still local. @pippinsplugins @mintplugins

**Comment by cklosowski** [comment]
I believe this should be a NEW issue, and related to better discovery of files outside of the content directory, that are local...not sure how we can do it yet, but that's the real issue here.

**Comment by pippinsplugins** [comment]
The problem is that `filesize()` is failing on that file. The file in question is given as full URL and is stored locally, though outside of standard upload folders.

Probably just need to add error suppression to `filesize()`.

**Comment by cklosowski** [comment]
@pippinsplugins the one in the example was not a full URL though it was a relative one we couldn't detect properly. That's the iffy part on relative files outside of content directories...are they paths or are they URLs, so in this case it's trying as a path...but I'm guessing the person meant for it to be a URL.

**Comment by cklosowski** [comment]
Adding error suppression will stop the notice, though.

**Comment by pippinsplugins** [comment]
It was a relative path because I asked Phil to have the user test it with a
relative path. Both relative path and URL resulted in the error.

**Comment by cklosowski** [comment]
Ah, gotcha. Yeah let's just suppress the errors on it.

**Comment by cklosowski** [comment]
this is the right move, we already suppress the errors on our other usage of `filesize()`

```
function edd_readfile_chunked( $file, $retbytes = true ) {

	$chunksize = 1024 * 1024;
	$buffer    = '';
	$cnt       = 0;
	$handle    = @fopen( $file, 'r' );

	if ( $size = @filesize( $file ) ) {
		header("Content-Length: " . $size );
	}
```
