### ISSUE TITLE
Taxes should be affected by negative fees.

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#4658]
If you have a negative fee on the cart, it will still charge tax as if no negative fee was added. 

![100 -off-discounttax-issue](https://cloud.githubusercontent.com/assets/1638128/15841850/3bea7966-2c22-11e6-9d52-6a148dea54d1.jpg)

**Comment by mintplugins** [comment]
Related: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/4632

**Comment by mintplugins** [comment]
This affects any function that uses negative fees including:

- Discounts Pro
- Points and Rewards

**Comment by pippinsplugins** [comment]
I'm pretty sure this is resolved in the same way as #4632

**Comment by mintplugins** [comment]
That's definitely possible. Just to clarify, I am running this test on the 2.6 branch and it is still occurring. However, https://github.com/easydigitaldownloads/easy-digital-downloads/issues/4632 is resolved.

**Comment by pippinsplugins** [comment]
Yeah, will still likely require a small change.

**Comment by pippinsplugins** [comment]
@mintplugins mind giving that PR a try? It's definitely not working 100% now but I _think_ it's better.

**Comment by mintplugins** [comment]
Testing...

**Comment by mintplugins** [comment]
That definitely fixed the issue for Point and Rewards. However, Discount Pro still seems to be affected

<img width="887" alt="screen shot 2016-06-07 at 9 39 43 pm" src="https://cloud.githubusercontent.com/assets/1638128/15880131/756eab90-2cf8-11e6-8817-593e780fbc1e.png">

**Comment by chriscct7** [comment]
That screenshot looks fine to me, what's wrong with it

**Comment by mintplugins** [comment]
@chriscct7 it's using the "Points and Rewards" extension - not Discounts pro. Here's one with a Discounts Pro discount:

<img width="863" alt="screen shot 2016-06-07 at 11 21 29 pm" src="https://cloud.githubusercontent.com/assets/1638128/15881778/a5f09d92-2d06-11e6-9d89-8691b5d5c866.png">

**Comment by mintplugins** [comment]
Okay so doing further testing, it's not a Points and Rewards VS Discounts Pro issue. The issue is whether the discount cover 100% of the original price. If the discount iis for 100% it is fine. If it is not for 100% the issue remains.

**Comment by chriscct7** [comment]
What's your tax rate set to?

**Comment by pippinsplugins** [comment]
@chriscct7 He said it above. 20%.

**Comment by cklosowski** [comment]
Ok, so in the case of Phil's situation above, the issue is that the item fee is reducing the price from `$10` to `$5`, however the tax being applied is `$2` or `20% of $10`. The problem is the item isn't costing the original `$10`, so the tax on the item shouldn't be `$2`, but `20% of $5` or `$1`, brining the total to `$6` instead of `$7`.

I think we need to make item specific fees affect the `subtotal` in order to properly account for things like this. Would we agree @mintplugins @pippinsplugins @chriscct7

**Comment by pippinsplugins** [comment]
I agree. Negative fees should apply before tax is calculated on the item, but only in the case that the fee is assigned to a download.

**Comment by mintplugins** [comment]
Yes I agree

**Comment by cklosowski** [comment]
Cool thanks guys. I'll get working on this then.

**Comment by mintplugins** [comment]
👍

**Comment by cklosowski** [comment]
@mintplugins @pippinsplugins ok, test this out for me if you can with the latest commits. You won't hurt my feelings if this doesn't work perfectly, this was a pretty difficult thing to try and get working right. Please test it out with things that do fees on items and the overall cart.

**Comment by pippinsplugins** [comment]
$10 item, 20% tax, 10% discount through Discounts Pro. Amounts look good!

![screen shot 2016-06-21 at 12 16 52 pm](https://cloud.githubusercontent.com/assets/1034109/16239360/1c53e874-37aa-11e6-8c01-5040ba69f397.png)

**Comment by cklosowski** [comment]
@pippinsplugins try it with simple shipping too, as that will add a positive fee that should be taxed.

**Comment by pippinsplugins** [comment]
Eh, actually here's something wrong.
![screen shot 2016-06-21 at 12 18 39 pm](https://cloud.githubusercontent.com/assets/1034109/16239412/4dca47ea-37aa-11e6-88f8-938312cf3909.png)

The final item amount post-purchase is not showing the discount.

**Comment by cklosowski** [comment]
@pippinsplugins will need to check the receipt template, maybe missed something there in how it's calculating.

**Comment by pippinsplugins** [comment]
Actually that's a separate issue. It's the same way in `master` and `release/2.6`. While definitely an issue, let's ignore that for now. Not related.

**Comment by cklosowski** [comment]
:+1:

**Comment by pippinsplugins** [comment]
With a discount from Discounts Pro and a fee from Simple Shipping:
![screen shot 2016-06-21 at 12 21 56 pm](https://cloud.githubusercontent.com/assets/1034109/16239521/c9e76be6-37aa-11e6-9679-b9b1f9ff2074.png)

All amounts check out.

**Comment by cklosowski** [comment]
@mintplugins would love you to go over this once as well, since you've tested plenty of the scenarios

**Comment by SDavisMedia** [comment]
Just went through all the scenarios I could think of with positive and negative fees and taxes. All amounts checking out for me as well.

**Comment by cklosowski** [comment]
Awesome. I'm going to merge this into `release/2.6` then! Thanks guys.

**Comment by mintplugins** [comment]
It's back in `prices inclusive of tax` only
