### ISSUE TITLE
All customer downloads not shown in "View customer download logs" screen

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/easy-digital-downloads#5373]
When viewing a customer's download logs, all the logs aren't shown. I haven't dug into it, so I'm not sure where the disconnect is. Example on the EDD site:

Customer download logs: https://easydigitaldownloads.com/wp-admin/edit.php?post_type=download&page=edd-reports&tab=logs&user=47603

Purchase log for same customer: https://easydigitaldownloads.com/wp-admin/edit.php?post_type=download&page=edd-reports&tab=logs&payment=989069

Another purchase log from same customer: https://easydigitaldownloads.com/wp-admin/edit.php?post_type=download&page=edd-reports&tab=logs&payment=989044

Also, in the customer log, it only shows one download of the Bookings product. He downloaded it 3 times, which is shown on the purchase download log view.

**Comment by ghost1227** [comment]
I've been trying to sort this out, but haven't found the disconnect yet. Any thoughts would be appreciated.

**Comment by pippinsplugins** [comment]
@ghost1227 have you replicated it?

**Comment by ghost1227** [comment]
Not with any sort of pattern or consistency

**Comment by mindctrl** [comment]
If you use the user's email instead of the user ID, you get them all (it seems). https://easydigitaldownloads.com/wp-admin/edit.php?post_type=download&page=edd-reports&tab=logs&user=info%40firstfloormedia.com


https://github.com/easydigitaldownloads/easy-digital-downloads/blob/64d11791d42897a8b0b3da62ecf071baf91feec6/includes/admin/reporting/class-file-downloads-logs-list-table.php#L225-L234

Why the 2 different meta keys? It would seem `_edd_log_user_id` isn't getting saved all the time?

**Comment by pippinsplugins** [comment]
Definitely looks like it's due to the user ID not being saved.

We should really look into converting the download log to only ever storing the customer ID so that the data is consistent between logged in and logged out customers.

**Comment by sunnyratilal** [comment]
@mindctrl Do you mind testing this on a local install with `release/3.0` as the active branch. @JJJ and I have revamped all the logs so it's more than likely that the issue was fixed.

**Comment by mindctrl** [comment]
@sunnyratilal it looks like it still isn't working.

I'm using the `View customer download log` link on the payment details screen. This has a URL like: `http://3dd.local/wp-admin/edit.php?post_type=download&page=edd-tools&tab=logs&user=2`.

As far as I can see, there's nothing in the log class that filters based on `$_GET['user']`.

**Comment by mindctrl** [comment]
@sunnyratilal PR: https://github.com/easydigitaldownloads/easy-digital-downloads/pull/6639

**Comment by sunnyratilal** [comment]
Tested and merged.
